# Site settings
title: This week in julia
email: thisweekinjulia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple blog to track major changes to the Julia language and ecosystem
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thisweekinjulia.github.io"
# twitter_username: jekyllrb
github_username:  thisweekinjulia
future: false

# Build settings
markdown: kramdown
